### ISSUE TITLE
Error :: SyntaxError: Non-ASCII character '\xc2' in file .\ransomware.py 

### ISSUE THREAD

**Issue by TanasanJJ7** [Chibraax/Ransomware#1]
![image](https://user-images.githubusercontent.com/16222517/92916223-817ce700-f457-11ea-8dd1-b665538e3bcc.png)

How to Fix.

**Comment by Chibraax** [comment]
I suppose you execute the code with a python2 interpreter. This error mean you have a encoding problem. By default no encoding is select in python2

I made this ransomware with Python.3.6 . Try to execute the code with a Python3 interpreter.
